using System.Diagnostics;
using WBDropp.Models;

namespace WBDropp.Services;

public sealed class DropletRunner
{
    private static readonly TimeSpan SaveTimeout = TimeSpan.FromMinutes(3);
    private readonly string _dropletDirectory;

    public DropletRunner(string? baseDirectory = null)
    {
        _dropletDirectory = Path.Combine(baseDirectory ?? AppContext.BaseDirectory, "droplers");
    }

    public string GetDropletPath(DropletKind kind) => Path.Combine(_dropletDirectory, kind switch
    {
        DropletKind.Modern => "Кадрирование.exe",
        DropletKind.ModernCloseUp => "Кадрирование_крупняк.exe",
        DropletKind.Legacy => "Legacy_Кадрирование.exe",
        DropletKind.LegacyCloseUp => "Legacy_Кадрирование_крупняк.exe",
        _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, null)
    });

    public void ValidateDroplets()
    {
        foreach (var kind in Enum.GetValues<DropletKind>())
        {
            var path = GetDropletPath(kind);
            if (!File.Exists(path)) throw new FileNotFoundException($"Не найден Photoshop-droplet: {Path.GetFileName(path)}", path);
        }
    }

    public async Task ProcessAsync(string imagePath, DropletKind kind, CancellationToken cancellationToken)
    {
        var dropletPath = GetDropletPath(kind);
        var before = new FileInfo(imagePath);
        var beforeLength = before.Length;
        var beforeWrite = before.LastWriteTimeUtc;

        using var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = dropletPath,
                UseShellExecute = false,
                CreateNoWindow = true,
                WorkingDirectory = Path.GetDirectoryName(imagePath) ?? AppContext.BaseDirectory
            }
        };
        process.StartInfo.ArgumentList.Add(imagePath);

        if (!process.Start()) throw new InvalidOperationException($"Не удалось запустить {Path.GetFileName(dropletPath)}");
        await process.WaitForExitAsync(cancellationToken);
        // Photoshop droplets generated by CC return 1 even after a successful
        // hand-off. The saved file is the source of truth, so 0 and 1 are valid.
        if (process.ExitCode is not 0 and not 1)
            throw new InvalidOperationException($"{Path.GetFileName(dropletPath)} завершился с кодом {process.ExitCode}.");

        var started = Stopwatch.StartNew();
        DateTime? stableSince = null;
        long lastLength = -1;
        DateTime lastWrite = DateTime.MinValue;

        while (started.Elapsed < SaveTimeout)
        {
            cancellationToken.ThrowIfCancellationRequested();
            await Task.Delay(250, cancellationToken);

            var current = new FileInfo(imagePath);
            current.Refresh();
            if (!current.Exists) continue;

            var changed = current.Length != beforeLength || current.LastWriteTimeUtc != beforeWrite;
            if (!changed) continue;

            if (current.Length == lastLength && current.LastWriteTimeUtc == lastWrite)
            {
                stableSince ??= DateTime.UtcNow;
                if (DateTime.UtcNow - stableSince >= TimeSpan.FromMilliseconds(750)) return;
            }
            else
            {
                stableSince = null;
                lastLength = current.Length;
                lastWrite = current.LastWriteTimeUtc;
            }
        }

        throw new TimeoutException($"Photoshop не сохранил файл за {SaveTimeout.TotalMinutes:0} мин.: {Path.GetFileName(imagePath)}");
    }
}
